[background]
image     = "grapes.LOCAL.jpg"
[[pass]]
clear     = [0.0, 0.0, 0.0, 1.0]
draw      = {mode = "triangles", count = 1}
vertex    = "../../rust/grimoire/examples/share/fullscreen_triangle.glsl"
fragment  = "./image.glsl"
background = "background"
